name: build
on: [push, pull_request]
# on:
#   push:
#     branches:
#     - master
#     - release-*
#     - v*
#     tags:
#     - v*
#   pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    steps:
    # Git is not in Dapper container image. Add it manually for dirty check.
    - name: Add Git
      run: apk add -U git
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Declare some variables
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"

    # For multi-platform support
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build binaries
    - name: Run dapper ci
      # run: dapper ci
      run: dapper build
      # env:
      #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Copy bin folder to package
      run: |
        ls -al
        ls -al ./bin
        cp -r ./bin/harvester-* ./package/
        cp -r ./bin/upgrade-helper-* ./package/upgrade/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # rancher/harvester image
    - name: docker-publish-harvester
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: frankyang/harvester:${{ env.branch }}-head
        file: package/Dockerfile
        build-args: |
          VERSION=${{ env.branch }}-${{ env.sha_short }}-head
    - name: docker-publish-harvester-with-tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: frankyang/harvester:${{ github.ref_name }}
        file: package/Dockerfile
        build-args: |
          VERSION=${{ github.ref_name }}
    - name: docker-manifest-harvester
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      run: |
        docker manifest create frankyang/harvester:${{ env.branch }}-head \
          frankyang/harvester:${{ env.branch }}-head-amd64 \
          frankyang/harvester:${{ env.branch }}-head-arm64

    # rancher/harvester-webhook image
    - name: docker-publish-harvester-webhook
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: frankyang/harvester-webhook:${{ env.branch }}-head
        file: package/Dockerfile.webhook
        build-args: |
          VERSION=${{ env.branch }}-${{ env.sha_short }}-head
    - name: docker-publish-harvester-webhook-with-tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: frankyang/harvester-webhook:${{ github.ref_name }}
        file: package/Dockerfile.webhook
        build-args: |
          VERSION=${{ github.ref_name }}

    # rancher/harvester-upgrade image
    - name: docker-publish-harvester-upgrade
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/upgrade
        push: true
        platforms: linux/amd64,linux/arm64
        tags: frankyang/harvester-upgrade:${{ env.branch }}-head
        file: package/upgrade/Dockerfile
        build-args: |
          VERSION=${{ env.branch }}-${{ env.sha_short }}-head
    - name: docker-publish-harvester-upgrade-with-tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/upgrade
        push: true
        platforms: linux/amd64,linux/arm64
        tags: frankyang/harvester-upgrade:${{ github.ref_name }}
        file: package/upgrade/Dockerfile
        build-args: |
          VERSION=${{ github.ref_name }}
